### ISSUE TITLE
NMFk example script on windows

### ISSUE THREAD

**Issue by osumpcheng** [lanl/T-ELF#175]
I'm wondering if the NMFk functionality is available in Windows environment. I installed it and tested the NMFk example script, I got error message says 'fcntl' module is not available, which seems like an Linux specific package. Are there any solutions to this? thank you!

**Comment by MaksimEkin** [comment]
The locking mechanism with ```fcntl``` is not available on Windows. May I suggest running T-ELF on a Virtual Machine.

Closing as tool is not designed for Windows.
